services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bank-ticket-password
      POSTGRES_DB: bank-ticket
    ports:
      - "5000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: