spring.datasource.url=jdbc:postgresql://localhost:5000/bank-ticket
spring.datasource.username=postgres
spring.datasource.password=bank-ticket-password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

