CREATE TABLE departments(
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    tag VARCHAR(5) UNIQUE NOT NULL,
    priority_tag VARCHAR(5) UNIQUE NOT NULL
);